from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .receipt import canonical_hash, verify_receipt


def _digest(data: Any) -> str:
    if isinstance(data, dict):
        return canonical_hash(data)
    encoded = json.dumps(data, sort_keys=True, separators=(",", ":")).encode()
    import hashlib

    return hashlib.sha256(encoded).hexdigest()


def _trace_id(case_id: str, receipt_hash: str) -> str:
    return canonical_hash({"case_id": case_id, "receipt_sha256": receipt_hash})[:32]


def build_carrier_summary(run: dict[str, Any], receipt: dict[str, Any]) -> str:
    """Render a portable MCP/OTel carrier receipt from a verified local run.

    This is not a live signed JWS or deployed gateway claim. It binds the current
    fixture proof to the fields a production MCP gateway could place in `_meta`
    and in an always-on audit log so judges can see exactly what would travel
    with a denied tool call.
    """
    case_id = run.get("case_id", receipt.get("case_id", "unknown"))
    receipt_hash = receipt.get("receipt_sha256", "missing")
    security = run.get("security", {})
    normalized = run.get("normalized_case", {})
    proposal = run.get("proposal", {}).get("policy", {})
    requested_tool = normalized.get("requested_action") or proposal.get("requested_action", "unknown")
    actor = normalized.get("stakeholder", "unknown")
    decision = security.get("verdict", "UNKNOWN")
    trace_id = _trace_id(case_id, receipt_hash)
    input_digest = _digest(run.get("raw_case", {}))
    result_digest = _digest({
        "verification": run.get("verification", {}),
        "security": security,
        "proposal": run.get("proposal", {}),
    })

    meta_rows = [
        ("org.agentproof/receipt_ref", f"sha256:{receipt_hash}", "portable pointer to this proof packet"),
        ("org.agentproof/trace_id", trace_id, "correlates gateway `_meta`, logs, and receipt"),
        ("org.agentproof/server", "agentproof-fixture-gateway", "fixture stand-in; not a live deployed gateway"),
        ("org.agentproof/tool", requested_tool, "requested high-risk capability before execution"),
        ("org.agentproof/access_decision", decision, "policy/security verdict bound to the carrier"),
        ("org.agentproof/policy_ref", "approval-gated-financial-action.v0", "human approval required for refund side effects"),
        ("org.agentproof/input_sha256", input_digest, "raw case bound by digest, not exposed in carrier"),
        ("org.agentproof/result_sha256", result_digest, "decision result bound by digest"),
        ("org.agentproof/tool_definition_ref", "mcp_tools.lock.json", "tool schema/behavior lock checked by `make verify`"),
        ("org.agentproof/redaction_applied", "true", "carrier uses digests and IDs instead of raw sensitive payloads"),
    ]
    meta_table = ["| MCP carrier key | Fixture value | Why judges should care |", "|---|---|---|"]
    meta_table.extend(f"| `{key}` | `{value}` | {note} |" for key, value, note in meta_rows)

    audit_rows = [
        ("event_name", "mcp.audit.tool_call", "low-cardinality audit event for the tool request"),
        ("outcome", "failure" if decision == "BLOCK" else "success", "blocked calls are recorded, not hidden"),
        ("actor_id", actor, "authenticated caller placeholder retained before authorization"),
        ("target", requested_tool, "tool/action being governed"),
        ("trace_id", trace_id, "same correlation id as the MCP carrier"),
        ("params_digest", input_digest, "hash of inputs; avoids leaking raw arguments"),
        ("result_digest", result_digest, "hash of verifier/security result"),
        ("receipt_sha256", receipt_hash, "tamper-evident exit artifact"),
    ]
    audit_table = ["| Audit field | Fixture value | Evidence role |", "|---|---|---|"]
    audit_table.extend(f"| `{field}` | `{value}` | {note} |" for field, value, note in audit_rows)

    return "\n".join([
        "# Portable MCP receipt carrier",
        "",
        "Generated by `make verify` from the deterministic fixture run and verified receipt. It shows the exact digest, decision, trace, and audit fields a future live MCP gateway could attach to a denied `tools/call` response, without claiming a deployed gateway, live OAuth, signed JWS, or real refund execution.",
        "",
        "## MCP `_meta` carrier sketch",
        "",
        *meta_table,
        "",
        "## always-on audit event sketch",
        "",
        *audit_table,
        "",
        "## source-backed design pressure",
        "",
        "- GOAI Agent Infra asks for execution evidence, approval/rollback boundaries, security auditability, and verifiable tool/MCP contracts.",
        "- MCP gateway receipt patterns bind access decisions, input/result digests, policy references, trace correlation, and tool-definition references so auditors can verify what the gateway reported without raw logs.",
        "- MCP audit/OTel projects warn that audit records should be always-on evidence, not sampled span decoration; AgentProof keeps a deterministic receipt first and can later export OTel-shaped events.",
        "",
        "## next live upgrade",
        "",
        "Add one read-only MCP tool call that returns these carrier fields in `_meta`, then keep this deterministic fixture as the CI fallback.",
        "",
    ])


def carrier_summary_from_paths(run_path: Path, receipt_path: Path, out: Path) -> str:
    ok, actual = verify_receipt(receipt_path)
    if not ok:
        raise ValueError(f"receipt hash mismatch, actual={actual}")
    run = json.loads(run_path.read_text())
    receipt = json.loads(receipt_path.read_text())
    summary = build_carrier_summary(run, receipt)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(summary)
    return summary
