from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .receipt import verify_receipt


def _evidence_ids(run: dict[str, Any]) -> str:
    ids = [item.get("source_id", "unknown") for item in run.get("evidence", [])]
    return ", ".join(ids) if ids else "none"


def build_gateway_trace(run: dict[str, Any], receipt: dict[str, Any]) -> str:
    """Render a fixture-backed MCP/gateway request-path trace for judges.

    This is intentionally not a live gateway claim. It maps the deterministic
    fixture run onto the gateway controls AgentProof expects a real MCP/A2A
    gateway to enforce later: caller identity, tool intent, evidence binding,
    policy verdict, approval boundary, and side-effect execution state.
    """
    normalized = run.get("normalized_case", {})
    security = run.get("security", {})
    verification = run.get("verification", {})
    proposal = run.get("proposal", {}).get("policy", {})
    receipt_hash = receipt.get("receipt_sha256", "missing")
    requested_action = normalized.get("requested_action") or proposal.get("requested_action", "unknown")
    approval_state = "missing" if not security.get("approval_present") else "present"
    tool_decision = security.get("verdict", "UNKNOWN")
    side_effect = "not executed" if receipt.get("no_external_side_effect_executed") else "executed_or_unknown"

    rows = [
        ("gateway mode", "fixture replay", "local deterministic stand-in; no live MCP gateway claimed"),
        ("caller / tenant", normalized.get("stakeholder", "unknown"), "actor retained before tool authorization"),
        ("requested tool", requested_action, "high-risk tool intent isolated before execution"),
        ("evidence binding", _evidence_ids(run), "source IDs bound into receipt before policy decision"),
        ("verifier gate", verification.get("verdict", "UNKNOWN"), f"failures={len(verification.get('failures', []))}"),
        ("policy / security decision", tool_decision, "; ".join(security.get("reasons", [])) or "no reasons recorded"),
        ("human approval", approval_state, "required for high-risk financial/legal side effects"),
        ("external side effect", side_effect, f"blocked={security.get('blocked_side_effect', 'none')}"),
        ("audit receipt", receipt_hash, "tamper-evident output of the request path"),
    ]

    table = ["| Gateway checkpoint | Observed value | Judge-visible meaning |", "|---|---|---|"]
    table.extend(f"| {name} | {value} | {meaning} |" for name, value, meaning in rows)

    return "\n".join([
        "# MCP gateway request-path trace",
        "",
        "Generated by `make verify` from the deterministic fixture run and receipt. It turns AgentProof's current local proof into the same checkpoint sequence a live MCP/A2A gateway should enforce later, without claiming a deployed gateway, live OAuth, or real external refund execution.",
        "",
        *table,
        "",
        "## source-backed design pressure",
        "",
        "- AgentTeams / HiClaw: Manager/Worker/Human collaboration should stay visible, with credentials and risky capability boundaries outside worker prompts.",
        "- MCP gateway projects: useful control planes put auth/RBAC, allowlists, audit logs, OpenTelemetry, rate limits, and denial events on the live request path, not only in after-action docs.",
        "- Winning multi-agent hackathon projects: judges reward a short, replayable control path where supervisor/worker actions, tool use, observability, and human approval are legible in one screen.",
        "",
        "## next live upgrade",
        "",
        "Swap this fixture replay for one low-risk read-only MCP gateway call while preserving the same checkpoint table, receipt hash binding, and deterministic fixture fallback.",
        "",
    ])


def gateway_trace_from_paths(run_path: Path, receipt_path: Path, out: Path) -> str:
    ok, actual = verify_receipt(receipt_path)
    if not ok:
        raise ValueError(f"receipt hash mismatch, actual={actual}")
    run = json.loads(run_path.read_text())
    receipt = json.loads(receipt_path.read_text())
    summary = build_gateway_trace(run, receipt)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(summary)
    return summary
