from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .carrier_summary import _digest, _trace_id
from .receipt import canonical_hash, verify_receipt


def build_identity_summary(run: dict[str, Any], receipt: dict[str, Any]) -> str:
    """Render an identity / authority boundary receipt for the fixture run.

    This deliberately avoids claiming live DID, OAuth, delegated credential, or
    signed JWS execution. It makes the authority chain that exists in the local
    proof explicit so a judge can see who requested action, who may approve, what
    was denied, and which digest-bound artifact would later be wrapped by a real
    MCP identity layer.
    """
    case_id = run.get("case_id", receipt.get("case_id", "unknown"))
    receipt_hash = receipt.get("receipt_sha256", "missing")
    trace_id = _trace_id(case_id, receipt_hash)
    normalized = run.get("normalized_case", {})
    raw_case = run.get("raw_case", {})
    security = run.get("security", {})
    proposal = run.get("proposal", {}).get("policy", {})
    requester = normalized.get("stakeholder", raw_case.get("stakeholder", "unknown"))
    requested_tool = normalized.get("requested_action") or proposal.get("requested_action", "unknown")
    requires_approval = proposal.get("requires_human_approval", False)
    approval_present = security.get("approval_present", False)
    blocked_side_effect = security.get("blocked_side_effect", "none")
    authority_digest = canonical_hash(
        {
            "case_id": case_id,
            "requester": requester,
            "requested_tool": requested_tool,
            "requires_human_approval": requires_approval,
            "approval_present": approval_present,
            "security_verdict": security.get("verdict", "UNKNOWN"),
            "receipt_sha256": receipt_hash,
        }
    )

    boundary_rows = [
        ("responsible party", "enterprise finance/compliance owner", "business owner remains accountable; not delegated to the model"),
        ("agent identity", "AgentProof fixture team", "local multi-agent runtime identity for this proof run"),
        ("requesting actor", requester, "caller recorded before authorization decision"),
        ("requested authority", requested_tool, "high-risk capability being governed"),
        ("approval authority", "human reviewer required", "financial side effect needs explicit approval"),
        ("approval evidence", "absent" if not approval_present else "present", "fixture intentionally demonstrates the deny path"),
        ("policy decision", security.get("verdict", "UNKNOWN"), f"blocked_side_effect={blocked_side_effect}"),
        ("external execution", "not executed", "model cannot self-authorize or bypass the gate"),
    ]
    boundary_table = ["| Boundary | Fixture value | Judge-visible meaning |", "|---|---|---|"]
    boundary_table.extend(f"| {name} | `{value}` | {note} |" for name, value, note in boundary_rows)

    portable_rows = [
        ("org.agentproof/authority_ref", f"sha256:{authority_digest}", "digest of who asked, what authority was requested, and gate result"),
        ("org.agentproof/responsible_party", "enterprise finance/compliance owner", "future DID/OAuth subject would bind here"),
        ("org.agentproof/requester", requester, "caller identity placeholder, not trusted from model text"),
        ("org.agentproof/approval_required", str(bool(requires_approval)).lower(), "machine-checkable policy boundary"),
        ("org.agentproof/approval_present", str(bool(approval_present)).lower(), "why the side effect was denied"),
        ("org.agentproof/trace_id", trace_id, "same correlation id used by the carrier/audit receipt"),
        ("org.agentproof/receipt_ref", f"sha256:{receipt_hash}", "tamper-evident proof packet pointer"),
        ("org.agentproof/raw_case_sha256", _digest(raw_case), "input is bound without exposing raw payload in carrier metadata"),
    ]
    portable_table = ["| Portable authority key | Fixture value | Evidence role |", "|---|---|---|"]
    portable_table.extend(f"| `{key}` | `{value}` | {note} |" for key, value, note in portable_rows)

    return "\n".join([
        "# Identity and authority boundary receipt",
        "",
        "Generated by `make verify` from the deterministic fixture run and verified receipt. It makes the authority chain judge-visible: the requester can ask for a refund, the model can propose and verify evidence, but the side effect remains non-executable without human approval.",
        "",
        "## delegated-authority boundary",
        "",
        *boundary_table,
        "",
        "## portable identity / authority carrier sketch",
        "",
        *portable_table,
        "",
        "## source-backed design pressure",
        "",
        "- KYA-OS-style MCP identity work emphasizes agent identity, delegated authority, consent gating, revocation, request/response hashes, and proof metadata that remains invisible to the model but verifiable by an auditor.",
        "- AGNTCY-style infrastructure emphasizes cross-framework agent discovery, identity, messaging, and observability as common infrastructure rather than app-specific prompt glue.",
        "- LinkedIn's enterprise multi-agent architecture shows a production pattern Abel can cite carefully: agents as registered capabilities, existing messaging as durable coordination, human-in-the-loop control, and OpenTelemetry-compatible production observability.",
        "",
        "## non-claims / upgrade path",
        "",
        "This fixture does not claim live DID, OAuth, JWS signing, token vaulting, real refund execution, or external identity-provider integration. Next upgrade: wrap one read-only MCP tool with a real caller identity and return this authority digest in `_meta` while keeping the deterministic deny fixture as CI fallback.",
        "",
    ])


def identity_summary_from_paths(run_path: Path, receipt_path: Path, out: Path) -> str:
    ok, actual = verify_receipt(receipt_path)
    if not ok:
        raise ValueError(f"receipt hash mismatch, actual={actual}")
    run = json.loads(run_path.read_text())
    receipt = json.loads(receipt_path.read_text())
    summary = build_identity_summary(run, receipt)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(summary)
    return summary
