from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .carrier_summary import _digest, _trace_id
from .receipt import canonical_hash, verify_receipt


def build_ops_metrics_summary(run: dict[str, Any], receipt: dict[str, Any]) -> str:
    """Render a judge-readable operations and observability receipt.

    The fixture has no live OpenTelemetry collector, latency meter, token meter, or
    gateway runtime yet. This summary therefore exposes only deterministic counters
    available in the run artifact, plus the exact OTel-shaped fields AgentProof
    should emit when a live gateway/AgentTeams path is connected.
    """
    case_id = run.get("case_id", receipt.get("case_id", "unknown"))
    receipt_hash = receipt.get("receipt_sha256", "missing")
    trace_id = _trace_id(case_id, receipt_hash)
    steps = run.get("steps", [])
    handoffs = run.get("handoffs", [])
    evidence = run.get("evidence", [])
    security = run.get("security", {})
    verification = run.get("verification", {})
    raw_case = run.get("raw_case", {})
    agents = sorted({step.get("agent", "unknown") for step in steps})
    actions = [step.get("action", "unknown") for step in steps]
    blocked = security.get("blocked_side_effect", "none")
    decision = security.get("verdict", "UNKNOWN")
    ops_digest = canonical_hash(
        {
            "case_id": case_id,
            "trace_id": trace_id,
            "agent_count": len(agents),
            "step_count": len(steps),
            "handoff_count": len(handoffs),
            "evidence_count": len(evidence),
            "verification_verdict": verification.get("verdict", "UNKNOWN"),
            "security_verdict": decision,
            "blocked_side_effect": blocked,
            "receipt_sha256": receipt_hash,
        }
    )

    metric_rows = [
        ("agent roles", len(agents), "distinct workers observed in fixture trace"),
        ("agent steps", len(steps), "ordered work units available for future spans"),
        ("typed handoffs", len(handoffs), "Manager/Worker-style context transitions"),
        ("evidence sources", len(evidence), "source artifacts bound before policy decision"),
        ("verification failures", len(verification.get("failures", [])), "deterministic result gate output"),
        ("policy decision", decision, f"blocked_side_effect={blocked}"),
        ("external side effects", "0 executed", "fixture blocks the refund path without approval"),
        ("live cost/latency", "not measured", "no live gateway/OTel collector in this fixture run"),
    ]
    metric_table = ["| Signal | Fixture value | Judge-visible meaning |", "|---|---:|---|"]
    for name, value, note in metric_rows:
        metric_table.append(f"| {name} | `{value}` | {note} |")

    span_rows = [
        ("trace_id", trace_id, "correlates trace, carrier, identity, receipt, and future OTel export"),
        ("span candidates", " → ".join(actions), "one span per current agent action"),
        ("service.name", "agentproof-os", "stable service identity for collector dashboards"),
        ("gen_ai.operation.name", "multi_agent_verification", "maps run to an AI-agent operation"),
        ("agentproof.policy.decision", decision, "policy result is queryable without parsing prose"),
        ("agentproof.receipt.sha256", receipt_hash, "tamper-evident artifact pointer"),
        ("agentproof.input.sha256", _digest(raw_case), "input-bound without exposing raw sensitive payload"),
        ("agentproof.ops.digest", ops_digest, "stable digest of the deterministic ops counters"),
    ]
    span_table = ["| OTel-shaped field | Fixture value | Why judges should care |", "|---|---|---|"]
    span_table.extend(f"| `{key}` | `{value}` | {note} |" for key, value, note in span_rows)

    agent_list = ", ".join(agents)
    return "\n".join([
        "# Operations metrics and observability receipt",
        "",
        "Generated by `make verify` from the deterministic fixture run and verified receipt. It turns the current run into a compact operations view: what ran, what was checked, what was blocked, and which fields should become live OpenTelemetry/gateway metrics later.",
        "",
        "## fixture-backed operations counters",
        "",
        *metric_table,
        "",
        "## OpenTelemetry / gateway export sketch",
        "",
        *span_table,
        "",
        "## agent roster",
        "",
        f"`{agent_list}`",
        "",
        "## source-backed design pressure",
        "",
        "- Alibaba Cloud's Agent Infra framing treats observability, evaluation, governance, memory, security, and operations as lifecycle infrastructure; runtime costs can become a black hole without per-team/per-agent attribution.",
        "- Agentgateway and ContextForge both make gateway-level auth, policy, rate limits, OpenTelemetry logs/metrics/traces, and tool-call observability part of production MCP/A2A infrastructure.",
        "- CMDR-style deterministic replay shows why trace capture should feed CI gates: frozen tool responses let reviewers compare behavioral changes without blaming live API variance.",
        "",
        "## non-claims / next upgrade",
        "",
        "This fixture does not claim a live OTel collector, AgentLoop, SigNoz, Jaeger, token-cost meter, latency benchmark, or deployed gateway. Next upgrade: emit this same counter set as JSON plus one real low-risk MCP tool span, then keep the deterministic fixture as the CI fallback.",
        "",
    ])


def ops_metrics_summary_from_paths(run_path: Path, receipt_path: Path, out: Path) -> str:
    ok, actual = verify_receipt(receipt_path)
    if not ok:
        raise ValueError(f"receipt hash mismatch, actual={actual}")
    run = json.loads(run_path.read_text())
    receipt = json.loads(receipt_path.read_text())
    summary = build_ops_metrics_summary(run, receipt)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(summary)
    return summary
