from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .receipt import verify_receipt


def _exists_status(path: Path) -> str:
    return "present" if path.exists() else "missing"


def build_proof_index(run: dict[str, Any], receipt: dict[str, Any], artifact_paths: dict[str, Path]) -> str:
    """Render a one-screen judge packet index across all generated proof artifacts."""
    verification = run.get("verification", {})
    security = run.get("security", {})
    case_id = run.get("case_id", receipt.get("case_id", "unknown"))
    receipt_hash = receipt.get("receipt_sha256", "missing")
    agent_count = len({step.get("agent") for step in run.get("steps", [])})
    handoff_count = len(run.get("handoffs", []))
    evidence_sources = ", ".join(row.get("source_id", "unknown") for row in run.get("evidence", []))

    packet_rows = [
        ("run trace", artifact_paths["run_md"], "ordered AgentTeams-style handoffs and worker ledger"),
        ("receipt JSON", artifact_paths["receipt_json"], "tamper-evident machine-readable execution receipt"),
        ("receipt proof table", artifact_paths["receipt_md"], "compact core signals and receipt hash"),
        ("control surface", artifact_paths["control_md"], "policy / approval / side-effect gate on the request path"),
        ("demo health", artifact_paths["health_md"], "offline fallback, no-key mode, and honest non-live scope"),
    ]
    packet_table = ["| Proof artifact | Path | Status | What it proves |", "|---|---|---|---|"]
    packet_table.extend(
        f"| {name} | `{path.as_posix()}` | {_exists_status(path)} | {proof} |"
        for name, path, proof in packet_rows
    )

    claim_rows = [
        ("case id", case_id, "same id binds run, receipt, and summaries"),
        ("agent roles", str(agent_count), ">=3 distinct agents required by GOAI Agent Infra"),
        ("typed handoffs", str(handoff_count), "context passing is explicit and ordered"),
        ("evidence sources", evidence_sources or "none", "source IDs are retained in the decision path"),
        ("deterministic verifier", verification.get("verdict", "UNKNOWN"), f"failures={len(verification.get('failures', []))}"),
        ("side-effect policy", security.get("verdict", "UNKNOWN"), f"blocked={security.get('blocked_side_effect', 'none')}"),
        ("receipt sha256", receipt_hash, "hashable exit artifact for reviewer replay"),
    ]
    claim_table = ["| Judge claim | Current value | Evidence note |", "|---|---|---|"]
    claim_table.extend(f"| {name} | {value} | {note} |" for name, value, note in claim_rows)

    return "\n".join([
        "# Judge proof packet index",
        "",
        "Generated by `make verify` from the deterministic fixture run and receipt.",
        "This is the fastest reviewer entrypoint: it links every judge-visible proof surface without claiming live external AgentTeams or MCP deployment.",
        "",
        "## artifact map",
        "",
        *packet_table,
        "",
        "## bound claims",
        "",
        *claim_table,
        "",
        "## replay command",
        "",
        "```bash",
        "make verify",
        "```",
        "",
    ])


def proof_index_from_paths(run_path: Path, receipt_path: Path, out: Path) -> str:
    ok, actual = verify_receipt(receipt_path)
    if not ok:
        raise ValueError(f"receipt hash mismatch, actual={actual}")
    run = json.loads(run_path.read_text())
    receipt = json.loads(receipt_path.read_text())
    artifact_paths = {
        "run_md": Path("artifacts/runs/latest.md"),
        "receipt_json": Path("artifacts/receipts/latest.json"),
        "receipt_md": Path("artifacts/receipts/latest.md"),
        "control_md": Path("artifacts/control/latest.md"),
        "health_md": Path("artifacts/health/latest.md"),
    }
    summary = build_proof_index(run, receipt, artifact_paths)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(summary)
    return summary
