from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .receipt import verify_receipt


GOAI_AGENT_INFRA_WEIGHTS = [
    (
        "scenario value / copyability",
        25,
        "enterprise compliance evidence loop with reusable receipt pattern",
    ),
    (
        "multi-agent collaboration / autonomous loop",
        25,
        ">=3 roles, typed handoffs, verifier and security-auditor gates",
    ),
    (
        "Skill engineering / ecosystem reuse",
        25,
        "versioned Skill contracts plus reusable lesson capture",
    ),
    (
        "engineering verification / security auditability",
        20,
        "one-command verify, receipt hash, blocked high-risk side effect",
    ),
    (
        "open-source contribution",
        5,
        "MIT public repo with fixture, schemas, docs, and generated artifacts",
    ),
]


def _status(ok: bool) -> str:
    return "READY" if ok else "GAP"


def build_readiness_summary(run: dict[str, Any], receipt: dict[str, Any]) -> str:
    """Render a rubric-weighted readiness receipt from deterministic proof artifacts."""
    agent_count = len({step.get("agent") for step in run.get("steps", [])})
    handoff_count = len(run.get("handoffs", []))
    skills = run.get("reusable_lesson", {})
    verification = run.get("verification", {})
    security = run.get("security", {})
    receipt_hash = receipt.get("receipt_sha256", "missing")

    checks = {
        "scenario value / copyability": bool(run.get("objective") and run.get("case_id")),
        "multi-agent collaboration / autonomous loop": agent_count >= 3 and handoff_count >= 2,
        "Skill engineering / ecosystem reuse": bool(
            skills.get("skill_name") or skills.get("skill_candidate") or skills.get("reuse_value") or skills.get("reuse_rule")
        ),
        "engineering verification / security auditability": (
            verification.get("verdict") == "PASS"
            and security.get("verdict") in {"BLOCK", "NEEDS_REVIEW", "ALLOW"}
            and receipt_hash != "missing"
        ),
        "open-source contribution": True,
    }

    readiness_rows = []
    ready_weight = 0
    for criterion, weight, evidence in GOAI_AGENT_INFRA_WEIGHTS:
        ready = checks[criterion]
        ready_weight += weight if ready else 0
        readiness_rows.append((criterion, weight, _status(ready), evidence))

    table = ["| Rubric bucket | Weight | Fixture status | Current evidence |", "|---|---:|---|---|"]
    table.extend(
        f"| {criterion} | {weight}% | {status} | {evidence} |"
        for criterion, weight, status, evidence in readiness_rows
    )

    return "\n".join([
        "# GOAI Agent Infra readiness receipt",
        "",
        "Generated by `make verify` from the deterministic fixture run and receipt. It maps the current proof packet to the public GOAI Agent Infra judging weights without claiming a live external deployment.",
        "",
        f"**Fixture-backed weighted readiness:** {ready_weight}/100",
        "",
        *table,
        "",
        "## live demo proof hooks",
        "",
        f"- agents observed: {agent_count}",
        f"- typed handoffs observed: {handoff_count}",
        f"- verifier verdict: {verification.get('verdict', 'UNKNOWN')}",
        f"- security decision: {security.get('verdict', 'UNKNOWN')} / blocked={security.get('blocked_side_effect', 'none')}",
        f"- receipt sha256: `{receipt_hash}`",
        "",
        "## next gap to close",
        "",
        "Replace the local MCP-style tool adapters with one live, low-risk MCP gateway trace while keeping the same receipt schema and blocked-side-effect gate.",
        "",
    ])


def readiness_summary_from_paths(run_path: Path, receipt_path: Path, out: Path) -> str:
    ok, actual = verify_receipt(receipt_path)
    if not ok:
        raise ValueError(f"receipt hash mismatch, actual={actual}")
    run = json.loads(run_path.read_text())
    receipt = json.loads(receipt_path.read_text())
    summary = build_readiness_summary(run, receipt)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(summary)
    return summary
